-- , Instructor(instructor_id, name, dept_id, salary, hire_date)
-- , Course(course_id, course_name, dept_id, credits, instructor_id)
-- , Student(student_id, name, dept_id, admission_year, email)
-- , Enrollment(enroll_id, student_id, course_id, semester, grade) 
-- , Department(dept_id, dept_name, building, budget)
-- , Course_Schedule(schedule_id, course_id, room_id, day_of_week, start_time)
-- , Book(book_id, title, author, dept_id, price)
-- , Book_Issue(issue_id, book_id, student_id, issue_date, return_date)
-- , Fee_Payment(payment_id, student_id, amount, payment_date, semester)


-- Produce a single summary report, one row per department, with the following columns:
--   * Department name
--   * Number of students in that department
--   * Number of instructors in that department
--   * Total number of enrollments generated by students of that department (across any course, any department)
--   * Total fees collected from students of that department (all semesters combined)


SELECT 
    d.dept_name, student_count, instructor_count, enrollment_count, total_amount
FROM Department d
LEFT JOIN (
    SELECT
        s.dept_id, COUNT(*) as student_count
    FROM Student s
    GROUP BY s.dept_id
) sc ON d.dept_id = sc.dept_id
LEFT JOIN (
    SELECT
        i.dept_id, COUNT(*) as instructor_count
    FROM Instructor i
    GROUP BY i.dept_id
) ic ON ic.dept_id = d.dept_id
LEFT JOIN (
    SELECT
        s.dept_id, COUNT(e.enroll_id) AS enrollment_count
    FROM Student s
    JOIN Enrollment e ON s.student_id = e.student_id
    GROUP BY s.dept_id
) ec ON ec.dept_id= d.dept_id
LEFT JOIN (
    SELECT
        s.dept_id, SUM(f.amount) AS total_amount
    FROM Student s
    JOIN Fee_Payment f ON f.student_id = s.student_id
    GROUP BY s.dept_id
) ft ON ft.dept_id = d.dept_id ; 